version: '3'

services:
  front:
    build:
      context: ./front
    ports:
      - "3000:3000"

  back:
    build:
      context: ./back
    ports:
      - "8080:8080"
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html

networks:
  default:
    external:
      name: mynetwork
